### ISSUE TITLE
backspace makes coc-pairs panic

### ISSUE THREAD

**Issue by damnever** [neoclide/coc-pairs#11]
Steps to reproduce:

1. Open a file.
2. Type something.
3. Trigger backspace key.

Error log:
```
2019-04-01T15:12:45.342 INFO (pid:5773) [completion-complete] - Results from: pyls,snippets,word
2019-04-01T15:12:48.344 ERROR (pid:5773) [attach] - Error on "doKeymap": TypeError: res[0] is not iterable
    at /Users/damnever/dotfiles/config/coc/extensions/node_modules/coc-pairs/lib/index.js:117:43
    at Generator.next (<anonymous>)
    at fulfilled (/Users/damnever/dotfiles/config/coc/extensions/node_modules/tslib/tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2019-04-01T15:12:48.432 INFO (pid:5773) [completion-complete] - Results from: snippets,around,word
2019-04-01T15:12:49.083 ERROR (pid:5773) [attach] - Error on "doKeymap": TypeError: res[0] is not iterable
    at /Users/damnever/dotfiles/config/coc/extensions/node_modules/coc-pairs/lib/index.js:117:43
    at Generator.next (<anonymous>)
    at fulfilled (/Users/damnever/dotfiles/config/coc/extensions/node_modules/tslib/tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by chemzqm** [comment]
It's problem of vim-node-rpc, it only return null for `call_atomic`, I've disabled backspace key-mapping on vim for now.
